import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { ComparisonProvider } from "@/context/ComparisonContext";
import ComparisonTray from "@/components/dashboard/comparison/Tray";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <ComparisonProvider>
          <main className="flex-1">{children}</main>
          <ComparisonTray />
        </ComparisonProvider>
      </body>
    </html>
  );
}
